version: "3.8"
services:
  frontend:
    build: .
    container_name: frontend-gastronomia-container
    ports:
      - "8083:80"
      - "8443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: always
